import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart' hide Trans;
import 'package:medora_git/common/widgets/nav_bar_painter.dart';
import 'package:medora_git/core/const/app_colors.dart';
import 'package:medora_git/core/theme/app_theme.dart';
import 'package:medora_git/features/doctor/business_layer/controller/doctor_controller.dart';
import 'package:medora_git/features/doctor/presentation/screens/doctor_appointments_screen.dart';
import 'package:medora_git/features/doctor/presentation/screens/doctor_consultations_screen.dart';
import 'package:medora_git/features/doctor/presentation/screens/doctor_home_screen.dart';
import 'package:medora_git/features/doctor/presentation/screens/doctor_settings_screen.dart';

/// Doctor app shell: the same bottom-nav style as the patient side, with a
/// center FAB that starts a new video consultation (Google Meet).
class DoctorMainScreen extends StatefulWidget {
  const DoctorMainScreen({super.key});

  @override
  State<DoctorMainScreen> createState() => _DoctorMainScreenState();
}

class _DoctorMainScreenState extends State<DoctorMainScreen> {
  int selectedIndex = 0;

  final pages = [
    DoctorHomeScreen(),
    DoctorAppointmentsScreen(),
    DoctorConsultationsScreen(),
    DoctorSettingsScreen(),
  ];

  @override
  void initState() {
    super.initState();
    Get.find<DoctorController>();
  }

  void changeTab(int index) {
    setState(() {
      selectedIndex = index;
    });
    // The tab pages stay alive, so re-fetch when the user comes back to
    // appointments/home instead of showing stale booking data.
    final controller = Get.find<DoctorController>();
    if (index == 0 || index == 1) {
      controller.fetchAppointments();
    }
  }

  double getSelectorPosition(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double itemWidth = width / 5;
    num positionIndex = selectedIndex < 2 ? selectedIndex : selectedIndex + 1;
    return itemWidth * positionIndex + (itemWidth / 2) - 26.36;
  }

  /// The FAB opens the consultations tab: Google Meet links exist only per
  /// online appointment (generated by the backend when the final payment
  /// completes it), so the doctor picks a consultation there and joins with
  /// its real link.
  void startConsultation() {
    setState(() => selectedIndex = 2);
  }

  Widget navItem(int index, String label, String icon, String selectedIcon) {
    final selected = index == selectedIndex;

    return Expanded(
      child: GestureDetector(
        onTap: () => changeTab(index),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SvgPicture.asset(
              selected ? selectedIcon : icon,
              width: 24.81,
              height: 24,
            ),
            const SizedBox(height: 4),
            Text(
              label,
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.w400,
                color: selected
                    ? context.appColors.primary
                    : context.appColors.textHint,
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.appColors;
    return Scaffold(
      backgroundColor: colors.background,
      extendBody: true,
      body: pages[selectedIndex],
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: Transform.translate(
        offset: const Offset(0, -10),
        child: InkWell(
          onTap: startConsultation,
          child: Container(
            height: 64.09,
            width: 62.01,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: context.appColors.primary,
              boxShadow: [
                BoxShadow(
                  color: AppColors.black.withValues(alpha: .25),
                  blurRadius: 7,
                  spreadRadius: 0,
                  offset: const Offset(0, -1),
                ),
              ],
            ),
            child: const Center(
              child: Icon(
                Icons.videocam_rounded,
                color: AppColors.white,
                size: 24,
              ),
            ),
          ),
        ),
      ),
      bottomNavigationBar: SizedBox(
        height: 69.22,
        child: Stack(
          children: [
            CustomPaint(
              size: const Size(double.infinity, 69.22),
              painter: NavBarPainter(
                fabRadius: 37.78,
                fillColor: colors.surface,
                shadowColor: colors.shadow,
                borderColor: colors.border,
              ),
            ),
            AnimatedPositioned(
              duration: const Duration(milliseconds: 300),
              curve: Curves.easeOut,
              top: 0,
              left: getSelectorPosition(context),
              child: Container(
                width: 52.72,
                height: 5,
                decoration: BoxDecoration(
                  color: AppColors.primary600,
                  borderRadius: BorderRadius.only(
                    bottomLeft: Radius.circular(18),
                    bottomRight: Radius.circular(18),
                  ),
                ),
              ),
            ),
            Row(
              children: [
                navItem(
                  0,
                  "home".tr(),
                  "assets/icons/home.svg",
                  "assets/icons/homes2.svg",
                ),
                navItem(
                  1,
                  "appointments".tr(),
                  "assets/icons/schedules.svg",
                  "assets/icons/schedules2.svg",
                ),
                const Spacer(),
                navItem(
                  2,
                  "consultations".tr(),
                  "assets/icons/patients.svg",
                  "assets/icons/patients2.svg",
                ),
                navItem(
                  3,
                  "settings".tr(),
                  "assets/icons/person.svg",
                  "assets/icons/profile2.svg",
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}